-- 050_ground_truth
--
-- Scenario definitions, the fourteen paired negative controls, and the metric
-- catalogue.
--
-- Scenarios record intent, never routes. The generator plants an opportunity;
-- the engine has to find the way through it. If this table held paths, the
-- evaluation would be checking that the engine can read.

INSERT INTO scenario (code, name, intent, expected_min_hops, expected_max_hops, expected_severity, sort_order) VALUES
  ('intern_to_domain_admin', 'Intern to domain admin',
   'A junior account is placed in a group whose nesting eventually confers administrative rights on a tier-zero host. No single grant looks wrong; the composition does.',
   4, 7, 9.50, 1),
  ('leaked_key_to_data',     'Leaked key to data exfiltration',
   'An access key is left in a publicly readable location and authenticates to storage connected to a database holding regulated data.',
   2, 4, 9.20, 2),
  ('kerberoast_to_app',      'Kerberoastable account to application server',
   'A service account carries a service principal name and a weak password, and holds administrative rights on an application server that trusts a database host.',
   3, 5, 8.40, 3),
  ('stale_vendor_vpn',       'Dormant vendor account into the internal network',
   'A vendor account nobody has reviewed retains a credential that authenticates to a VPN concentrator with a route into internal infrastructure.',
   3, 6, 8.10, 4),
  ('nested_group_cloud',     'Nested group escalation into cloud',
   'Three levels of group nesting terminate in a permission on a cloud resource that can assume a role on another.',
   4, 7, 7.80, 5),
  ('unpatched_edge_pivot',   'Unpatched edge device to internal pivot',
   'An internet-facing host is behind on patching for a remotely exploitable weakness and trusts an internal host.',
   3, 6, 8.80, 6),
  ('shared_cred_sprawl',     'Shared credential across service accounts',
   'One secret is reused by several service accounts, so compromising the weakest asset holding it confers the union of their access.',
   3, 5, 8.00, 7),
  ('ci_pipeline_to_prod',    'Build pipeline into production',
   'A deployment identity holds production write access and its credential is readable from a staging host with far weaker controls.',
   3, 6, 9.00, 8);


-- Every decoy ships with a twin that IS a valid path and differs in exactly one
-- attribute. Without twins, an engine that reports nothing scores perfectly on
-- precision; with them, passing requires actually evaluating the attribute.
INSERT INTO decoy_pattern (code, name, deciding_attribute, decoy_description, twin_description, rejection_rationale, attack_id, sort_order) VALUES
  ('d01_mfa_phishing_resistant', 'Phishing-resistant MFA', 'AUTHENTICATES_TO.mfa_type',
   'Authentication is gated by a hardware-backed factor.',
   'Identical, except the factor is SMS.',
   'Credential replay cannot satisfy a hardware-backed challenge; possessing the secret is not sufficient. SMS falls to relay and is therefore traversable, with a penalty.',
   'T1550', 1),
  ('d02_vaulted_credential', 'Vault-stored credential', 'Credential.storage',
   'A configuration file references a secret held in a vault.',
   'Identical, except the configuration file contains the secret itself.',
   'The asset holds a pointer, not material. Dumping the configuration yields a reference that still requires vault authentication.',
   'T1552.001', 2),
  ('d03_read_only_permission', 'Read-only group permission', 'HAS_PERMISSION.permission_level',
   'A group holds read-only permission on the asset.',
   'Identical, except the permission is administrative.',
   'Read access confers no ability to alter the asset or extract secrets from it, so the escalation the path depends on never occurs.',
   'T1078.002', 3),
  ('d04_disabled_account', 'Disabled account with live assignments', 'User.account_status',
   'A disabled account retains its administrative rights assignment.',
   'Identical, except the account is active.',
   'Rights assignments outlive accounts in every directory. The assignment is real; the ability to authenticate as the principal is not.',
   'T1078', 4),
  ('d05_one_way_trust', 'One-directional trust traversed backwards', 'TRUSTS.bidirectional',
   'A one-way trust, with the candidate path running against its direction.',
   'Identical, except the trust is bidirectional.',
   'Trust direction determines which host accepts authentication from which. Traversing against it is not an attack, it is a misreading of the graph.',
   'T1199', 5),
  ('d06_strong_spn_password', 'Kerberoastable account with a strong password', 'Credential.strength',
   'A service account carries an SPN and a long random password.',
   'Identical, except the password is weak.',
   'The ticket request succeeds; the offline crack does not. Reporting this as a path implies a capability the attacker cannot realise.',
   'T1558.003', 6),
  ('d07_patched_host', 'Fully patched host with a known CVE record', 'Host.patch_level',
   'A host is associated with a vulnerability but is fully patched.',
   'Identical, except the host is two cycles behind.',
   'A vulnerability association records history. A patched host is not exploitable through it.',
   'T1210', 7),
  ('d08_no_admin_for_dump', 'Credential exposure without administrative access', 'held capability',
   'A host exposes a credential in a configuration file; the attacker holds only unprivileged access.',
   'Structurally identical, except the attacker holds administrative control of the host.',
   'Reading a secret from an asset requires privileged access to that asset. The graph is identical in both cases and only the attacker state differs, which is precisely why reachability alone cannot decide it.',
   'T1552.001', 8),
  ('d09_segmented_network', 'Network segmentation', 'CONNECTED_TO presence',
   'Two resources with no connectivity between them.',
   'Identical, except a peering connection exists.',
   'Without a route there is no pivot. Segmentation is the control, and a tool that ignores it reports paths through air gaps.',
   'T1021', 9),
  ('d10_rotated_credential', 'Already-rotated credential', 'Credential.is_active',
   'A credential that has been rotated but whose records persist.',
   'Identical, except the credential is current.',
   'Rotated material does not authenticate. The record of it having existed is not a path.',
   'T1078', 10),
  ('d11_non_interactive_sa', 'Non-interactive service account', 'ServiceAccount.is_interactive',
   'A service account configured to deny interactive logon.',
   'Identical, except interactive logon is permitted.',
   'The credential is valid but the logon type the path requires is refused by policy.',
   'T1078.003', 11),
  ('d12_separate_key_required', 'Database requiring a separate key', 'Database.requires_separate_key',
   'An encrypted database whose data key the attacker does not hold.',
   'Identical, except no separate key is required.',
   'Authenticating to the instance is not the same as reading the data. Encryption at rest with independent key custody breaks the final step.',
   'T1530', 12),
  ('d13_distribution_group', 'Distribution group', 'Group.type',
   'A distribution group that appears to confer permission.',
   'Identical, except the group is a security group.',
   'Distribution groups address mail. They carry no authorisation, and a path through one is a path through a mailing list.',
   'T1078.002', 13),
  ('d14_device_compliance', 'Conditional access device requirement', 'AUTHENTICATES_TO.requires_compliant_device',
   'Authentication requires an enrolled, compliant device.',
   'Identical, except no device requirement applies.',
   'Valid credentials presented from an unmanaged device are refused before authorisation is even evaluated.',
   'T1078.004', 14);


INSERT INTO metric_definition (code, label, description, interpretation, family, higher_is_better, format, sort_order) VALUES
  ('precision_edge',   'Precision (edge sequence)',  'Fraction of reported paths corresponding to a genuine planted opportunity, matched on the exact edge sequence.',
   'Low precision means false positives: paths reported that an attacker could not actually walk.', 'discovery', 1, 'fraction', 1),
  ('recall_edge',      'Recall (edge sequence)',     'Fraction of planted opportunities the engine found, matched on the exact edge sequence.',
   'Low recall means missed attacks. Recall is trivial to maximise alone by reporting everything, so it is only meaningful beside precision.', 'discovery', 1, 'fraction', 2),
  ('f1_edge',          'F1 (edge sequence)',         'Harmonic mean of edge-sequence precision and recall.',
   'The headline discovery number. Punishes trading either half of the pair away for the other.', 'discovery', 1, 'fraction', 3),
  ('precision_node',   'Precision (node sequence)',  'As above, matched on nodes rather than edges.',
   'A gap between node and edge scores means the engine reaches the right places by the wrong mechanism.', 'discovery', 1, 'fraction', 4),
  ('recall_node',      'Recall (node sequence)',     'As above, matched on nodes rather than edges.',
   'Compare against edge recall to see how often the route is right but the technique is not.', 'discovery', 1, 'fraction', 5),
  ('decoy_rejection',  'Decoy rejection rate',       'Fraction of planted negative controls correctly refused.',
   'Directly measures false-positive resistance. Meaningful only alongside twin acceptance.', 'discovery', 1, 'fraction', 6),
  ('twin_acceptance',  'Twin acceptance rate',       'Fraction of decoy twins, which are genuine paths, correctly accepted.',
   'Guards against passing the decoy test by refusing everything. Both this and decoy rejection must be high for either to mean anything.', 'discovery', 1, 'fraction', 7),
  ('kendall_tau',      'Kendall tau',                'Rank correlation between the engine ordering and the ground-truth severity ordering.',
   'Measures whether the most dangerous paths appear at the top, which is what prioritisation means in practice.', 'ranking', 1, 'fraction', 8),
  ('ndcg_at_10',       'NDCG@10',                    'Normalised discounted cumulative gain over the top ten results.',
   'Weights errors near the top of the list more heavily, matching how an analyst actually reads it.', 'ranking', 1, 'fraction', 9),
  ('calibration_error','Expected calibration error', 'Mean gap between predicted probability and observed frequency, bucketed.',
   'When the engine says seventy percent, does it happen seventy percent of the time? A model can rank perfectly and still be badly calibrated.', 'calibration', 0, 'fraction', 10),
  ('brier_score',      'Brier score',                'Mean squared error of the probability estimates.',
   'Single-number summary of probabilistic accuracy. Lower is better.', 'calibration', 0, 'fraction', 11),
  ('oracle_agreement', 'Oracle agreement',           'Fraction of small graphs where the fast engine and the exhaustive reference return identical path sets.',
   'Anything below 1.0 means the two implementations disagree about what the rules mean, and one of them is wrong.', 'discovery', 1, 'fraction', 12),
  ('sim_exact_match',  'Simulation exact-match rate','Fraction of applied fixes whose actual effect exactly matched the prediction.',
   'Measures whether the counterfactual is trustworthy. This is remediation impact made checkable.', 'remediation', 1, 'fraction', 13),
  ('sim_jaccard',      'Simulation Jaccard',         'Overlap between the predicted and actual changed path sets.',
   'Softer companion to exact match; shows how close a near miss was.', 'remediation', 1, 'fraction', 14),
  ('discovery_ms',     'Discovery time',             'Wall-clock time for a full discovery run.',
   'An engine that is correct but slow is a different product from one that is correct and fast.', 'performance', 0, 'milliseconds', 15);
